// main/app_lang.c —— 中英文字符串表实现,见 app_lang.h。
// 设备端 UI 与远程管理网页的可见文案都从这里取值;网页按当前语言选择
// 对应变体(PAGE_*_ZH/EN,见 app_server.c),服务端 JSON 错误信息走 tr()。
#include "app_lang.h"

#include <stddef.h>

// 索引顺序必须与 app_lang.h 的 tr_id_t 枚举严格一致;宿主测试 tests/test_app_lang.c
// 校验两表等长、无空项。
static const char *const k_str[2][TR_ID_COUNT] = {
    // ---------------- 简体中文 ----------------
    {
        [TR_MENU_REMOTE] = "远程管理",
        [TR_MENU_WIFI] = "无线网络",
        [TR_MENU_LOCK] = "立即锁定",
        [TR_MENU_DELETE] = "删除条目",
        [TR_LANG_TOGGLE] = "English",
        [TR_WIFI_SCAN] = "扫描连接",
        [TR_WIFI_CLEAR] = "清除凭证",
        [TR_BACK] = "返回",
        [TR_RESCAN] = "重新扫描",
        [TR_KB_LOWER] = "abc",
        [TR_KB_UPPER] = "ABC",
        [TR_KB_DIGIT] = "123",
        [TR_KB_GROUP_SYM] = "符号",
        [TR_KB_SPACE] = "空格",
        [TR_KB_BACK] = "退格",
        [TR_KB_DONE] = "完成",
        [TR_CANCEL] = "取消",
        [TR_DELETE] = "删除",
        [TR_TITLE_CONFIRM] = "重复输入确认",
        [TR_TITLE_SETUP] = "创建密码",
        [TR_TITLE_UNLOCK] = "输入密码",
        [TR_HINT_SETUP] = "上/下 输入 · 确定 退格 · 长按 清空",
        [TR_HINT_MAIN] = "上/下 切换 · 确定 菜单 · 长按 锁定",
        [TR_HINT_MENU] = "上/下 选择 · 确定 进入 · 长按 返回",
        [TR_HINT_WIFI] = "上/下 选择 · 确定 执行 · 长按 返回",
        [TR_HINT_KB] = "上/下 选择 · 确定 录入 · 双击 退格 · 长按 完成",
        [TR_HINT_DELETE] = "上/下 选择 · 确定 确认",
        [TR_HINT_MGMT] = "长按确定退出",
        [TR_TITLE_MENU] = "菜单",
        [TR_TITLE_MGMT] = "远程管理",
        [TR_TITLE_WIFI] = "无线网络",
        [TR_TITLE_SCAN] = "扫描连接",
        [TR_SCANNING] = "正在扫描...",
        [TR_SCAN_FAIL] = "扫描失败",
        [TR_NO_ENTRIES] = "没有条目",
        [TR_ADD_VIA_REMOTE] = "请用远程管理添加",
        [TR_WAIT_SYNC] = "等待时间同步...",
        [TR_ENTRY] = "条目",
        [TR_MSG_REPEAT] = "请再次输入同样的序列",
        [TR_MSG_MISMATCH] = "不一致，请重新开始",
        [TR_MSG_NEED_WIFI] = "请先连接无线网络",
        [TR_MSG_START_FAIL] = "启动失败",
        [TR_MSG_NOTHING_TO_DELETE] = "没有可删除的条目",
        [TR_MSG_TOO_MANY] = "失败次数过多，暂不接受输入",
        [TR_MSG_PENALTY_OVER] = "惩罚结束，可以重试",
        [TR_WIFI_OFF] = "未启动",
        [TR_WIFI_IDLE] = "未配置",
        [TR_WIFI_CONNECTING] = "连接中",
        [TR_WIFI_CONNECTED] = "已连接",
        [TR_WIFI_AUTH_FAIL] = "密码错误？",
        [TR_WIFI_NO_AP] = "找不到网络",
        [TR_WIFI_RETRY_WAIT] = "重连中",
        [TR_WIFI_ERROR] = "错误",
        [TR_NOTE_WAITING] = "等待登录",
        [TR_NOTE_SESSION] = "会话已建立",
        [TR_NOTE_LOGOUT] = "已退出登录",
        [TR_NOTE_EXIT] = "网页请求退出",
        [TR_NOTE_LOCKED] = "尝试次数过多",
        [TR_FATAL_TITLE] = "存储错误",
        [TR_FATAL_BODY] = "NVS 不可用，拒绝启动。\n请检查闪存分区。",
        [TR_FMT_REFRESH] = "%us后刷新",
        [TR_FMT_DELETE_TITLE] = "删除 \"%s\"？",
        [TR_FMT_TRIES] = "错误，还可尝试 %d 次",
        [TR_FMT_LOCKED] = "锁定 %u:%02u",
        [TR_FMT_ATTEMPTS] = "%s · 剩余 %d 次",
        [TR_FMT_STATE] = "状态：%s",
        [TR_FMT_SSID] = "\n名称：%s",
        [TR_FMT_IP] = "\nIP：%s",
        [TR_KB_EMPTY] = "（空）",
        [TR_FMT_KB_COUNT] = "已输入 %u/64",
        [TR_FMT_KB_TITLE] = "无线密码：%s",
        // 远程管理网页与服务端 JSON
        [TR_WEB_LOGIN_PROMPT] = "输入设备屏幕上的 8 位数字码",
        [TR_WEB_SIGN_IN] = "登录",
        [TR_WEB_HEADING] = "条目管理",
        [TR_WEB_LOGOUT] = "退出登录",
        [TR_WEB_ADD_TITLE] = "添加条目",
        [TR_WEB_LABEL_NAME] = "名称（≤24 字节，约 8 个汉字）",
        [TR_WEB_LABEL_SECRET] = "密钥 Base32",
        [TR_WEB_LABEL_DIGITS] = "位数",
        [TR_WEB_LABEL_PERIOD] = "周期（秒）",
        [TR_WEB_NOTE] = "密钥只存入设备，不会通过网络返回。",
        [TR_WEB_ADD_BTN] = "添加",
        [TR_WEB_NO_ENTRIES] = "暂无条目",
        [TR_WEB_ADDED] = "已添加",
        [TR_WEB_DELETED] = "已删除",
        [TR_ERR_BAD_REQUEST] = "请求无效",
        [TR_ERR_UNAUTHORIZED] = "未授权",
        [TR_ERR_WRONG_CODE] = "验证码错误",
        [TR_ERR_LOCKED] = "已锁定，请在设备上重新开启",
        [TR_ERR_LABEL] = "名称需 1-24 个字符（支持中文）",
        [TR_ERR_SECRET] = "密钥不是有效的 Base32",
        [TR_ERR_RANGE] = "位数或周期超范围",
        [TR_ERR_FULL] = "存储已满",
        [TR_ERR_SAVE] = "保存失败",
        [TR_ERR_BAD_ID] = "编号无效",
        [TR_ERR_DELETE] = "删除失败",
        [TR_ERR_MISSING] = "字段缺失",
    },
    // ---------------- English ----------------
    {
        [TR_MENU_REMOTE] = "Remote Mgmt",
        [TR_MENU_WIFI] = "Wi-Fi",
        [TR_MENU_LOCK] = "Lock now",
        [TR_MENU_DELETE] = "Delete entry",
        [TR_LANG_TOGGLE] = "中文",
        [TR_WIFI_SCAN] = "Scan & connect",
        [TR_WIFI_CLEAR] = "Clear credentials",
        [TR_BACK] = "Back",
        [TR_RESCAN] = "Rescan",
        [TR_KB_LOWER] = "abc",
        [TR_KB_UPPER] = "ABC",
        [TR_KB_DIGIT] = "123",
        [TR_KB_GROUP_SYM] = "Sym",
        [TR_KB_SPACE] = "Space",
        [TR_KB_BACK] = "Bksp",
        [TR_KB_DONE] = "Done",
        [TR_CANCEL] = "Cancel",
        [TR_DELETE] = "Delete",
        [TR_TITLE_CONFIRM] = "Confirm password",
        [TR_TITLE_SETUP] = "Create password",
        [TR_TITLE_UNLOCK] = "Enter password",
        [TR_HINT_SETUP] = "UP/DOWN step · OK del · hold clear",
        [TR_HINT_MAIN] = "UP/DOWN switch · OK menu · hold lock",
        [TR_HINT_MENU] = "UP/DOWN select · OK go · hold back",
        [TR_HINT_WIFI] = "UP/DOWN select · OK go · hold back",
        [TR_HINT_KB] = "UP/DOWN sel · OK pick · dbl del · hold done",
        [TR_HINT_DELETE] = "UP/DOWN select · OK confirm",
        [TR_HINT_MGMT] = "Hold OK to exit",
        [TR_TITLE_MENU] = "Menu",
        [TR_TITLE_MGMT] = "Remote Mgmt",
        [TR_TITLE_WIFI] = "Wi-Fi",
        [TR_TITLE_SCAN] = "Scan & connect",
        [TR_SCANNING] = "Scanning...",
        [TR_SCAN_FAIL] = "Scan failed",
        [TR_NO_ENTRIES] = "No entries",
        [TR_ADD_VIA_REMOTE] = "Add keys via Remote Mgmt",
        [TR_WAIT_SYNC] = "Waiting for time sync...",
        [TR_ENTRY] = "entry",
        [TR_MSG_REPEAT] = "Repeat the same sequence",
        [TR_MSG_MISMATCH] = "Mismatch — start over",
        [TR_MSG_NEED_WIFI] = "Connect Wi-Fi first",
        [TR_MSG_START_FAIL] = "Start failed",
        [TR_MSG_NOTHING_TO_DELETE] = "No entries to delete",
        [TR_MSG_TOO_MANY] = "Too many failed attempts",
        [TR_MSG_PENALTY_OVER] = "Penalty over — try again",
        [TR_WIFI_OFF] = "off",
        [TR_WIFI_IDLE] = "not configured",
        [TR_WIFI_CONNECTING] = "connecting",
        [TR_WIFI_CONNECTED] = "connected",
        [TR_WIFI_AUTH_FAIL] = "wrong password?",
        [TR_WIFI_NO_AP] = "network not found",
        [TR_WIFI_RETRY_WAIT] = "reconnecting",
        [TR_WIFI_ERROR] = "error",
        [TR_NOTE_WAITING] = "Waiting for login",
        [TR_NOTE_SESSION] = "Session active",
        [TR_NOTE_LOGOUT] = "Logged out",
        [TR_NOTE_EXIT] = "Exit requested from web",
        [TR_NOTE_LOCKED] = "Too many failed attempts",
        [TR_FATAL_TITLE] = "Storage error",
        [TR_FATAL_BODY] = "NVS unavailable.\nRefusing to start.\nCheck flash partition.",
        [TR_FMT_REFRESH] = "Refresh in %us",
        [TR_FMT_DELETE_TITLE] = "Delete \"%s\"?",
        [TR_FMT_TRIES] = "Wrong, %d attempts left",
        [TR_FMT_LOCKED] = "Locked %u:%02u",
        [TR_FMT_ATTEMPTS] = "%s · %d attempts left",
        [TR_FMT_STATE] = "State: %s",
        [TR_FMT_SSID] = "\nSSID: %s",
        [TR_FMT_IP] = "\nIP: %s",
        [TR_KB_EMPTY] = "(empty)",
        [TR_FMT_KB_COUNT] = "Input %u/64",
        [TR_FMT_KB_TITLE] = "Wi-Fi password: %s",
        [TR_WEB_LOGIN_PROMPT] = "Enter the 8-digit code shown on the device",
        [TR_WEB_SIGN_IN] = "Sign in",
        [TR_WEB_HEADING] = "Entries",
        [TR_WEB_LOGOUT] = "Logout",
        [TR_WEB_ADD_TITLE] = "Add entry",
        [TR_WEB_LABEL_NAME] = "Label (up to 24 bytes, ~8 Chinese chars)",
        [TR_WEB_LABEL_SECRET] = "Secret (Base32)",
        [TR_WEB_LABEL_DIGITS] = "Digits",
        [TR_WEB_LABEL_PERIOD] = "Period (s)",
        [TR_WEB_NOTE] = "Secrets are stored on the device only.",
        [TR_WEB_ADD_BTN] = "Add",
        [TR_WEB_NO_ENTRIES] = "No entries",
        [TR_WEB_ADDED] = "Added",
        [TR_WEB_DELETED] = "Deleted",
        [TR_ERR_BAD_REQUEST] = "Bad request",
        [TR_ERR_UNAUTHORIZED] = "Unauthorized",
        [TR_ERR_WRONG_CODE] = "Wrong code",
        [TR_ERR_LOCKED] = "Locked, restart on device",
        [TR_ERR_LABEL] = "Label must be 1-24 characters",
        [TR_ERR_SECRET] = "Secret is not valid Base32",
        [TR_ERR_RANGE] = "Digits or period out of range",
        [TR_ERR_FULL] = "Storage full",
        [TR_ERR_SAVE] = "Save failed",
        [TR_ERR_BAD_ID] = "Bad id",
        [TR_ERR_DELETE] = "Delete failed",
        [TR_ERR_MISSING] = "Missing fields",
    },
};

static app_lang_t s_lang = APP_LANG_ZH;

const char *tr(tr_id_t id) {
    if ((int)id < 0 || id >= TR_ID_COUNT) return "";
    return k_str[s_lang][id];
}

void app_lang_set_current(app_lang_t lang) {
    if (lang == APP_LANG_ZH || lang == APP_LANG_EN) {
        s_lang = lang;
    }
}

app_lang_t app_lang_current(void) {
    return s_lang;
}

app_lang_t app_lang_toggle(void) {
    s_lang = s_lang == APP_LANG_ZH ? APP_LANG_EN : APP_LANG_ZH;
    return s_lang;
}
